In [34]:
import numpy as np

In [35]:
mylist = [1,2,3]

In [36]:
type(mylist)

list

In [37]:
np.array(mylist)

array([1, 2, 3])

In [38]:
mylist

[1, 2, 3]

In [39]:
myarray = np.array(mylist)

In [40]:
type(myarray)

numpy.ndarray

In [41]:
my_matrix = [[1,2,3],[4,5,6],[7,8,9]]

In [42]:
my_matrix

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [43]:
np.array(my_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
np.arange(0,100, 5)  #the 5 is the step size

array([ 0, 20, 40, 60, 80])

In [48]:
np.zeros(5) #create an array of 5 zeros

np.zeros((2,3)) #create a 2x3 array of zeros

array([[0., 0., 0.],
       [0., 0., 0.]])

In [49]:
np.ones(5) #creating an array of 5 ones

array([1., 1., 1., 1., 1.])

In [52]:
#starting-point, ending-point, number-of-elements
np.linspace(0,10,11) #create an array of 10 evenly spaced numbers between 0 and 5

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [53]:
np.eye(5) #create a 5x5 identity matrix

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [54]:
np.random.rand(5) #create an array of 5 random numbers between 0 and 1

array([0.05406395, 0.41664012, 0.22184595, 0.892399  , 0.51166692])

In [63]:
np.random.randn(5) #create an array of 5 random numbers from a standard normal distribution

array([ 0.90072569, -1.21887225, -1.40288733, -0.06360059, -0.86668849])

In [64]:
np.random.randint(1,100,5) #create an array of 5 random integers between 1 and 100

array([54, 47, 24, 23, 20], dtype=int32)

In [67]:
np.random.seed(42) #set a seed for reproducibility
np.random.rand(4) #create an array of 5 random numbers between 0 and 1 with the seed set

array([0.37454012, 0.95071431, 0.73199394, 0.59865848])

In [69]:
arr = np.arange(0,25)

In [70]:
arr.reshape(5,5) #reshape the array into a 5x5 matrix

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [71]:
ranarr = np.random.randint(0,101, 10) #create an array of 10 random integers between 0 and 50

In [ ]:
ranarr.max() #find the maximum value in the array

np.int32(2)

In [73]:
ranarr.min() #find the minimum value in the array

np.int32(2)

In [74]:
arr = np.arange(0, 11)

In [75]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [76]:
arr[8]

np.int64(8)

In [ ]:
arr[1:5] #slice the array from index 1 to 4

array([1, 2, 3, 4])

In [79]:
arr[:5]

array([0, 1, 2, 3, 4])